### ISSUE TITLE
Error when pressing a key while not on a signal

### ISSUE THREAD

**Issue by The72YT** [ElectricityMachine/SCR-SGPlus#1]
The tool is great, but whenever I press a key where there's no signal, the script shows an error and I have to open it again in order to get it working again.

**Comment by ElectricityMachine** [comment]
Hi! Thanks for trying it out.

Could you please post a screenshot of the error? In addition to that, please verify you have run the `pip install -r requirements.txt` command in the script's directory and that you are on the latest release version.

**Comment by The72YT** [comment]
Sure! I have installed Python 3.10.4 and the requirements without errors, but this happens when I click "1" over the black background of the signalling screen.

![image](https://user-images.githubusercontent.com/72730887/166110368-2057a689-b74a-49d5-890b-ae06f462d361.png)

**Comment by ElectricityMachine** [comment]
Thanks for the reply. I know what the issue could be, but am unsure why it's happening. I'm not able to reproduce on my end, so I wouldn't be able to test if the fix worked.

Based on this, are you able to add me on Discord using the contact info on the bottom of the README? This will require some one on one debugging to properly fix it. Thanks for reporting it!
