### ISSUE TITLE
Zone D message is censored

### ISSUE THREAD

**Issue by Dark-Humanities** [ElectricityMachine/SCR-SGPlus#46]
Roblox is censoring "Zone D (Morganstown to Leighton West) is now under manual signaling control."
and you should probably change it to "Zone D (Morganstown to LW) is now under manual signaling control."
See screenshot for more details
![Capture d'écran 2024-01-21 154629](https://github.com/ElectricityMachine/SCR-SGPlus/assets/63814600/fe84c9c7-dfe2-4e44-a6a3-98e1e2ba131b)

**Comment by ElectricityMachine** [comment]
Thanks for reporting this. Fixed by a88e85f97e97013059563399e78c5f8bc2973473.
