### ISSUE TITLE
Camera button not clicking

### ISSUE THREAD

**Issue by snalye** [ElectricityMachine/SCR-SGPlus#5]
When pressing C on the signal, the camera button isn't clicked
![image](https://user-images.githubusercontent.com/1113196/187114639-634d8c8c-dac5-45df-b1d9-dffd837ceafa.png)
With debug enabled
![image](https://user-images.githubusercontent.com/1113196/187114695-28bab89b-91b6-4a26-ba36-6a4e60d6949e.png)

**Comment by snalye** [comment]
Re-read the read me

**Comment by ElectricityMachine** [comment]
Should be resolved with [version 0.3.0](https://github.com/ElectricityMachine/SCR-SGPlus/releases/tag/v0.3.0). Let me know if you're still having issues.
